# Generated by Django 3.1.7 on 2021-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='titulo')),
                ('img', models.ImageField(height_field=1080, upload_to='', verbose_name='img', width_field=1920)),
                ('texto', models.TextField(max_length=1000, verbose_name='texto')),
            ],
        ),
    ]
