# Generated by Django 3.1.7 on 2021-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nankurunaisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='img',
            field=models.ImageField(upload_to='photos', verbose_name='img'),
        ),
    ]
