# Generated by Django 3.1.7 on 2021-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nankurunaisa', '0003_auto_20210329_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='img',
            field=models.ImageField(upload_to='static', verbose_name='img'),
        ),
    ]
