# Generated by Django 3.1.7 on 2021-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nankurunaisa', '0004_auto_20210330_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
